from resources import CHARACTERS, RESOURCES


likes = sum(
    [
        [
            "Aurora Borealis",
            "Rainbows",
            "Meteors",
            "Comets",
            "Solar Eclipses",
            "Lunar Eclipses",
            "Black Holes",
            "Supernovas",
            "Galaxies",
            "Auroras",
            "Tsunamis",
            "Tornadoes",
            "Volcanoes",
            "Lightning",
            "Clouds",
            "Stardust",
            "Nebulas",
            "Quasars",
            "Canyons",
            "Caves",
            "Geysers",
            "Hot Springs",
            "Mushrooms",
            "Glow Worms",
            "Stone Circles",
            "Coral Reefs",
            "Deserts",
            "Dunes",
            "Fjords",
            "Lakes",
            "Oceans",
            "Rivers",
            "Waterfalls",
            "Mountains",
            "Icebergs",
            "Glaciers",
            "Rainforests",
            "Jungles",
            "Savannas",
            "Tundra",
            "Forests",
            "Grasslands",
            "Hummocks",
            "Mangroves",
            "Marshes",
            "Moorlands",
            "Oases",
            "Ponds",
            "Prairies",
            "Swamps",
            "Terraces",
            "Underwater",
        ],
        [
            "Painting",
            "Drawing",
            "Photography",
            "Writing",
            "Gardening",
            "Knitting",
            "Crocheting",
            "Woodworking",
            "Home Brewing",
            "Pottery",
            "Jewelry Making",
            "Loom Weaving",
            "Tattooing",
            "Dancing",
            "Cooking",
            "Baking",
            "Hiking",
            "Camping",
            "Fishing",
            "Hunting",
            "Bird Watching",
            "Geocaching",
            "Collecting",
            "Painting",
            "Calligraphy",
            "Blogging",
            "Reading",
            "Programming",
            "Video Games",
            "Puzzles",
            "Tabletop Games",
            "Sewing",
            "Quilting",
            "Embroidery",
            "Doll Making",
            "Origami",
            "Kite Flying",
            "Modeling",
            "Racing",
            "Surfing",
            "Snowboarding",
            "Skateboarding",
            "Cycling",
            "Rock Climbing",
            "Archery",
            "Golfing",
            "Bowling",
            "Yoga",
            "Tai Chi",
            "Meditation",
            "Pilates",
            "Running",
            "Singing",
            "Fencing",
            "Scrapbooking",
            "Guitar",
            "Piano",
        ],
        [
            "Cat",
            "Dog",
            "Horse",
            "Cow",
            "Goat",
            "Sheep",
            "Pig",
            "Rabbit",
            "Mouse",
            "Squirrel",
            "Deer",
            "Fox",
            "Owl",
            "Hawk",
            "Eagle",
            "Raven",
            "Goose",
            "Duck",
            "Raccoon",
            "Skunk",
            "Opossum",
            "Coyote",
            "Beaver",
            "Frog",
            "Toad",
            "Turtle",
            "Snake",
            "Lizard",
            "Salamander",
            "Fish",
            "Shark",
            "Crab",
            "Lobster",
            "Oyster",
            "Clam",
            "Squid",
            "Octopus",
            "Moth",
            "Butterfly",
            "Caterpillar",
            "Bee",
            "Spider",
            "Wasp",
            "Ant",
            "Grasshopper",
            "Cricket",
            "Mantis",
            "Fly",
            "Termite",
            "Mole",
            "Vole",
            "Hedgehog",
            "Porcupine",
            "Giraffe",
            "Zebra",
            "Lion",
            "Tiger",
            "Leopard",
            "Cheetah",
            "Elephant",
            "Rhino",
            "Hippo",
            "Monkey",
            "Gorilla",
            "Chimpanzee",
            "Orangutan",
        ],
    ],
    [],
)


state_variables = {
    "messages": [],
    "primer": "I am an educational assistant for writing stories for children",
    "context_length": 10,
    "image": "",
    "story_data": {},
    "database": {
        "characters": CHARACTERS,
        "resources": RESOURCES,
        "materials": [],
        "likes": likes,
        "dislikes": likes,
        "personality": [
            "Happy",
            "Sad",
            "Excited",
            "Angry",
            "Bored",
            "Lonely",
            "Surprised",
            "Scared",
            "Confused",
            "Amused",
            "Glad",
            "Moody",
            "Tired",
            "Peaceful",
            "Jealous",
            "Grateful",
            "Curious",
            "Lively",
            "Impatient",
            "Enthusiastic",
            "Upset",
            "Shy",
            "Energetic",
            "Brave",
            "Calm",
            "Lazy",
            "Jumpy",
            "Generous",
            "Cheerful",
            "Funny",
            "Optimistic",
            "Brave",
            "Careful",
            "Loyal",
            "Polite",
            "Proud",
            "Relaxed",
            "Organized",
            "Cautious",
            "Sensitive",
            "Youthful",
            "Content",
            "Eager",
            "Brave",
            "Caring",
            "Adventurous",
            "Inquisitive",
        ],
        "gender": ["male", "female", ""],
        "hair colour": [
            "Black",
            "Blonde",
            "Brown",
            "Brunette",
            "Auburn",
            "Chestnut",
            "Red",
            "Golden",
            "Silver",
            "White",
            "Gray",
            "Strawberry Blonde",
        ],
        "eye colour": [
            "Amber",
            "Blue",
            "Brown",
            "Gray",
            "Green",
            "Hazel",
            "Red",
            "Violet",
            "Pink",
        ],
        "wearing": [
            "a T-shirt",
            "a Shirt",
            "Jeans",
            "Pants",
            "a Skirt",
            "Shorts",
            "Dress",
            "Jacket",
            "Coat",
            "Sweater",
            "Hat",
            "Gloves",
            "Scarves",
            "Socks",
        ],
        "lives_in": [
            "Forest",
            "City",
            "Beach",
            "Desert",
            "Mountain",
            "Lake",
            "River",
            "Cave",
            "Valley",
            "Jungle",
            "Island",
            "Savanna",
            "Swamp",
            "Volcano",
            "Bay",
            "Rainforest",
            "Glacier",
            "Oasis",
            "Grassland",
            "Cliff",
            "Plateau",
            "Meadow",
            "Park",
            "Dunes",
            "Fjord",
            "Peninsula",
            "Gulf",
            "Promontory",
            "Tundra",
            "Coast",
            "Archipelago",
            "Springs",
            "Glen",
            "Falls",
            "Basin",
            "Rapids",
            "Canyon",
            "Butte",
            "Ravine",
            "Ridge",
            "Chaparral",
            "Delta",
            "Steppe",
            "Cove",
            "Cape",
            "Bluffs",
            "Strait",
            "Lagoon",
            "Gorge",
            "Chasm",
            "Loch",
            "Moor",
            "Headland",
            "Scarps",
            "Mesa",
            "Moraine",
            "Prairie",
            "Hills",
            "Pass",
            "Foothills",
            "Crater",
            "City",
        ],
        "flair": [
            "Book",
            "Journal",
            "Sketchbook",
            "Camera",
            "Phone",
            "Wallet",
            "Sunglasses",
            "Umbrella",
            "Flashlight",
            "Pen",
            "Pencil",
            "Keys",
            "Watch",
            "Earphones",
            "Gum",
            "Snacks",
            "Lip Balm",
            "Hairbrush",
            "Mirror",
            "Compass",
            "Perfume",
            "Lotion",
            "Scarf",
            "Hat",
            "Gloves",
            "Bandana",
            "Backpack",
            "Tote Bag",
            "Purse",
            "Pack of Cards",
            "Notebook",
            "Bookmark",
            "Magnifying Glass",
            "Mini Telescope",
            "Coin",
            "Stamp",
            "Postcard",
            "Clipboard",
            "Pocket Knife",
            "Pipe",
            "Flask",
            "Lighter",
            "Matches",
            "Whistle",
            "Harmonica",
            "Guitar Pick",
            "Tiny Telescope",
            "Binoculars",
            "Magnets",
            "Glow Sticks",
            "Gems",
            "Rocks",
            "Marbles",
            "Feathers",
            "Shells",
            "Leaves",
            "Pine Cones",
            "Magnifying Glass",
            "Mini Telescope",
        ],
    },
    "tasks": [],
}
